#!/bin/bash
# Reset the quenched-m25 RT trees before the 2026-08 campaign launch.
#
# The selection changed on 2026-08-05 (new cut: M_dust/M_H2 >= 1e-4, 152 -> ~101
# galaxies), so the staged trees are wholesale stale: July agn rtouts ran pre-bhfix
# ("No BH found") at 1e7 photons, the agn tree still has the dropped z=0.6 snap_120,
# and the ids/gal dirs reflect the old 152-galaxy sample.
#
# Everything below is regenerated by re-running notebook Parts 2-3 (+3b) and Part 5
# (selection h5 + masters + submit scripts; the makesed snap<100 fix is deployed, so
# snap_078 is now included automatically). The filtered_particles cutouts are NOT
# touched — the survivors' cutouts are reused as-is.
set -euo pipefail

BASE=/mnt/home/glorenzon/analize_simba_cgm/output/cis25/sed_quenched_regions

for run in dusty_simdust dusty_simdust_agn nodust_1e-12; do
  echo "Removing $BASE/$run"
  rm -rf "$BASE/$run"
done

echo "Done. Now re-run notebook Parts 0-3, 3b, then Part 5, then:"
echo "  for r in dusty_simdust nodust_1e-12 dusty_simdust_agn; do"
echo "    bash \$BASE/\$r/powderday_sed_out/submit_all_snaps.sh"
echo "  done"
